name: Auto Run PHP Japan Proxy

on:
  schedule:
    - cron: "*/60 * * * *"  # tiap 7 menit
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ secrets.SC_TOKEN }}
        run: php tester.php
